/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Character } from '../models';
import { CharacterBankLog } from '../models';
import { CharacterPlaytime } from '../models';
import { Storages } from '../models';
/**
 * OwnApi - axios parameter creator
 * @export
 */
export const OwnApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Own Banklogs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selfBanklogsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/self/banklogs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication vio_auth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("vio_auth", ["read.group.info", "read.group.members", "read.group.storage", "read.group.storage.logs", "read.group.vehicles", "read.group.area", "read.group.shop", "read.group.factory", "read.group.ownfactory", "read.group.shops", "read.self.info", "read.self.storage", "read.self.playingtime"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Own Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selfGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/self`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication vio_auth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("vio_auth", ["read.group.info", "read.group.members", "read.group.storage", "read.group.storage.logs", "read.group.vehicles", "read.group.area", "read.group.shop", "read.group.factory", "read.group.ownfactory", "read.group.shops", "read.self.info", "read.self.storage", "read.self.playingtime"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Own Playingtime statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selfPlayingtimeGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/self/playingtime`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication vio_auth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("vio_auth", ["read.group.info", "read.group.members", "read.group.storage", "read.group.storage.logs", "read.group.vehicles", "read.group.area", "read.group.shop", "read.group.factory", "read.group.ownfactory", "read.group.shops", "read.self.info", "read.self.storage", "read.self.playingtime"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Own Storage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selfStorageGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/self/storage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication vio_auth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("vio_auth", ["read.group.info", "read.group.members", "read.group.storage", "read.group.storage.logs", "read.group.vehicles", "read.group.area", "read.group.shop", "read.group.factory", "read.group.ownfactory", "read.group.shops", "read.self.info", "read.self.storage", "read.self.playingtime"])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OwnApi - functional programming interface
 * @export
 */
export const OwnApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Own Banklogs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfBanklogsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<CharacterBankLog>>>> {
            const localVarAxiosArgs = await OwnApiAxiosParamCreator(configuration).selfBanklogsGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Own Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Character>>> {
            const localVarAxiosArgs = await OwnApiAxiosParamCreator(configuration).selfGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Own Playingtime statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfPlayingtimeGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<CharacterPlaytime>>>> {
            const localVarAxiosArgs = await OwnApiAxiosParamCreator(configuration).selfPlayingtimeGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Own Storage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfStorageGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Storages>>> {
            const localVarAxiosArgs = await OwnApiAxiosParamCreator(configuration).selfStorageGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * OwnApi - factory interface
 * @export
 */
export const OwnApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get Own Banklogs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfBanklogsGet(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<CharacterBankLog>>> {
            return OwnApiFp(configuration).selfBanklogsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Own Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfGet(options?: AxiosRequestConfig): Promise<AxiosResponse<Character>> {
            return OwnApiFp(configuration).selfGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Own Playingtime statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfPlayingtimeGet(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<CharacterPlaytime>>> {
            return OwnApiFp(configuration).selfPlayingtimeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Own Storage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selfStorageGet(options?: AxiosRequestConfig): Promise<AxiosResponse<Storages>> {
            return OwnApiFp(configuration).selfStorageGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OwnApi - object-oriented interface
 * @export
 * @class OwnApi
 * @extends {BaseAPI}
 */
export class OwnApi extends BaseAPI {
    /**
     * 
     * @summary Get Own Banklogs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OwnApi
     */
    public async selfBanklogsGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<CharacterBankLog>>> {
        return OwnApiFp(this.configuration).selfBanklogsGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Own Data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OwnApi
     */
    public async selfGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<Character>> {
        return OwnApiFp(this.configuration).selfGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Own Playingtime statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OwnApi
     */
    public async selfPlayingtimeGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<CharacterPlaytime>>> {
        return OwnApiFp(this.configuration).selfPlayingtimeGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Own Storage
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OwnApi
     */
    public async selfStorageGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<Storages>> {
        return OwnApiFp(this.configuration).selfStorageGet(options).then((request) => request(this.axios, this.basePath));
    }
}
