/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CharacterBankLog
 */
export interface CharacterBankLog {
    /**
     * 
     * @type {number}
     * @memberof CharacterBankLog
     */
    characterID?: number;
    /**
     * 
     * @type {number}
     * @memberof CharacterBankLog
     */
    timestamp?: number;
    /**
     * 
     * @type {string}
     * @memberof CharacterBankLog
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterBankLog
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterBankLog
     */
    info?: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterBankLog
     */
    info1?: string;
}
