/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Character
 */
export interface Character {
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    ID?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    accountID: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    playingtime?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    gender: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    STVO: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    vehicleLimit: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    busExp?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    spawn?: string;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    spawnID?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    wanteds?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    jailTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    methTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    weaponLicenseA?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    weaponLicenseB?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    weaponLicenseC?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    activityTimestamp?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    questID: string;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    questStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    phoneNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    factionTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    grade?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    raiting: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    drivingLicenseA?: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    foodStatus: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    activityStep: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    drivingLicensesBlockedTimestamp?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    wantedArchiv?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    skin?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    skills?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    dailyQuests?: string;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    bonusVehicleLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    accessory?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    achievements?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    totalStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    activeStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    skillPoints?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    skillBranches?: string;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    skillSync: number;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    expBoost?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    tattoos?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    licenses?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    dailyBonus?: string;
}
