/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CharacterPlaytime
 */
export interface CharacterPlaytime {
    /**
     * 
     * @type {number}
     * @memberof CharacterPlaytime
     */
    ID?: number;
    /**
     * 
     * @type {number}
     * @memberof CharacterPlaytime
     */
    timestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof CharacterPlaytime
     */
    minutes?: number;
}
