/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GangArea
 */
export interface GangArea {
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    ID: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    distriktID: number;
    /**
     * 
     * @type {string}
     * @memberof GangArea
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    X: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    Y: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    Z: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    range: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    rotation: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    owner: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    lastAttack: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    itemID: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    impact: number;
    /**
     * 
     * @type {number}
     * @memberof GangArea
     */
    oldOwner: number;
}
