/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupMember
 */
export interface GroupMember {
    /**
     * 
     * @type {number}
     * @memberof GroupMember
     */
    characterID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupMember
     */
    groupID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupMember
     */
    rank: number;
    /**
     * 
     * @type {number}
     * @memberof GroupMember
     */
    activity: number;
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    permissions: string;
    /**
     * 
     * @type {number}
     * @memberof GroupMember
     */
    lastActivity: number;
    /**
     * 
     * @type {boolean}
     * @memberof GroupMember
     */
    online?: boolean;
}
