/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupShop
 */
export interface GroupShop {
    /**
     * 
     * @type {number}
     * @memberof GroupShop
     */
    shopId: number;
    /**
     * 
     * @type {number}
     * @memberof GroupShop
     */
    money: number;
    /**
     * 
     * @type {number}
     * @memberof GroupShop
     */
    mats: number;
}
