/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupLSPDEvidence
 */
export interface GroupLSPDEvidence {
    /**
     * 
     * @type {number}
     * @memberof GroupLSPDEvidence
     */
    characterID?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupLSPDEvidence
     */
    characterName?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupLSPDEvidence
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof GroupLSPDEvidence
     */
    timestamp: string;
}
