/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupSkin
 */
export interface GroupSkin {
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    gangID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    torso: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    torsoTexture: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    legs: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    legsTexture: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    feet: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    feetTexture: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    accessories: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    undershirt: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    undershirtTexture: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    tops: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    topsTexture: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    gender: number;
    /**
     * 
     * @type {number}
     * @memberof GroupSkin
     */
    primKey?: number;
}
