/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupFactory
 */
export interface GroupFactory {
    /**
     * 
     * @type {number}
     * @memberof GroupFactory
     */
    ID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupFactory
     */
    groupID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupFactory
     */
    storage: number;
    /**
     * 
     * @type {number}
     * @memberof GroupFactory
     */
    nextCapture: number;
    /**
     * 
     * @type {number}
     * @memberof GroupFactory
     */
    craftingStorage?: number;
}
