/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupLSPDBlacklist
 */
export interface GroupLSPDBlacklist {
    /**
     * 
     * @type {number}
     * @memberof GroupLSPDBlacklist
     */
    groupID: number;
    /**
     * 
     * @type {string}
     * @memberof GroupLSPDBlacklist
     */
    groupName?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupLSPDBlacklist
     */
    expiry: number;
    /**
     * 
     * @type {string}
     * @memberof GroupLSPDBlacklist
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof GroupLSPDBlacklist
     */
    creator: string;
}
