/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupStorageLog
 */
export interface GroupStorageLog {
    /**
     * 
     * @type {number}
     * @memberof GroupStorageLog
     */
    groupID: number;
    /**
     * 
     * @type {string}
     * @memberof GroupStorageLog
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupStorageLog
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof GroupStorageLog
     */
    item: string;
    /**
     * 
     * @type {string}
     * @memberof GroupStorageLog
     */
    timestamp: string;
}
