/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupOwnFactory
 */
export interface GroupOwnFactory {
    /**
     * 
     * @type {number}
     * @memberof GroupOwnFactory
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupOwnFactory
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof GroupOwnFactory
     */
    groupID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupOwnFactory
     */
    masterID: number;
    /**
     * 
     * @type {string}
     * @memberof GroupOwnFactory
     */
    storage: string;
    /**
     * 
     * @type {string}
     * @memberof GroupOwnFactory
     */
    settings: string;
    /**
     * 
     * @type {string}
     * @memberof GroupOwnFactory
     */
    craftingStorages: string;
    /**
     * 
     * @type {number}
     * @memberof GroupOwnFactory
     */
    EXP: number;
}
