/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupSpray
 */
export interface GroupSpray {
    /**
     * 
     * @type {string}
     * @memberof GroupSpray
     */
    ID: string;
    /**
     * 
     * @type {number}
     * @memberof GroupSpray
     */
    groupID: number;
    /**
     * 
     * @type {string}
     * @memberof GroupSpray
     */
    sprayObject: string;
    /**
     * 
     * @type {number}
     * @memberof GroupSpray
     */
    timestamp: number;
}
