/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupRank
 */
export interface GroupRank {
    /**
     * 
     * @type {number}
     * @memberof GroupRank
     */
    rankID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupRank
     */
    groupID: number;
    /**
     * 
     * @type {string}
     * @memberof GroupRank
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GroupRank
     */
    bonus: number;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRank
     */
    leader: boolean;
}
