/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    ID: number;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    exp: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    level: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    server: number;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    msg: string;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    R?: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    G: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    B?: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    chatR: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    chatG: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    chatB: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    memberlimit: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    tag: number;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    rang0: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    rang1: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    rang2?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    rang3?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    rang4: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    rang5: string;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    lastExp: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    r2: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    g2: number;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    b2: number;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    boost1: number;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    skinMale: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    skinFemale: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    boosts: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    relationships: string;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    craftingStorage?: number;
}
