/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupVehicle
 */
export interface GroupVehicle {
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    ID: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    groupID: number;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    posX: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    posY: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    posZ: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    rotX: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    rotY: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    rotZ: string;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color1: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color2: number;
    /**
     * 
     * @type {Date}
     * @memberof GroupVehicle
     */
    buyDate: Date;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color1R: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color1G: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color1B: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color2R: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color2G: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    color2B: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    spoilers: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    frontBumper: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    rearBumper: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    sideSkirt: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    exhaust: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    frame: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    grille: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    hood: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    fender: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    rightFender: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    roof: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    engine: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    brakes: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    transmission: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    horns: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    suspension: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    armor: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    turbo: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    xenon: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    frontWheels: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    backWheels: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    plateholders: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    trimDesign: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    ornaments: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    dialDesign: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    steeringWheel: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    shiftLever: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    plaques: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    hydraulics: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    livery: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    plate: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    windowTint: number;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    modName: string;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    interiorColor: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    chipTuning: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    paintArt: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    wheelColor: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    wheelType: number;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    spawnGarage: number;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    lastDriver: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    plateText: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    fuel: string;
    /**
     * 
     * @type {number}
     * @memberof GroupVehicle
     */
    health: number;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    dirtLevel: string;
    /**
     * 
     * @type {string}
     * @memberof GroupVehicle
     */
    permission?: string;
}
