/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Storages
 */
export interface Storages {
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof Storages
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    typeId: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    maxSize: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item0: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item1: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item2: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item3: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item4: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item5: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item6: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item7: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item8: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item9: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item10: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item11: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item12: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item13: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item14: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item15: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item16: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item17: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item18: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item19: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item20: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item21: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item22: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item23: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item24: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item25: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item26: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item27: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item28: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item29: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item30: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item31: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item32: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item33: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item34: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item35: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item36: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item37: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item38: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item39: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item40: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item41: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item42: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item43: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item44: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item45: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item46: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item47: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item48: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item49: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item50: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item51: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item52: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item53: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item54: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item55: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item56: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item57: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item58: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item59: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item60: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item61: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item62: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item63: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item64: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item65: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item66: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item67: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item68: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item69: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item70: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item71: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item72: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item73: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item74: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item75: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item76: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item77: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item78: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item79: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item80: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item81: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item82: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item83: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item84: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item85: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item86: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item87: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item88: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item89: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item90: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item91: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item92: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item93: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item94: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item95: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item96: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item97: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item98: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item99: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item100: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item101: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item102: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item103: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item104: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item105: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item106: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item107: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item108: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item109: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item110: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item111: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item112: number;
    /**
     * 
     * @type {number}
     * @memberof Storages
     */
    item113: number;
}
