/* tslint:disable */
/* eslint-disable */
/**
 * Vio-V
 * Vio-V API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SystemItem
 */
export interface SystemItem {
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    ID: number;
    /**
     * 
     * @type {string}
     * @memberof SystemItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemItem
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    legal: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    heal: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    food: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    priceMin: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    priceMax: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    allowTrade: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    sync: number;
    /**
     * 
     * @type {number}
     * @memberof SystemItem
     */
    onlyOnce: number;
}
